tvkitchen/appliances

package.json, src/Payload.js, src/__test__/AbstractAppliance.test.js, src/utils/__test__/payload.test.js, src/utils/payload.js, yarn.lock
This PR replaces the local `Payload` implementation and instead imports the `Payload` from the [@tvkitchen/base-classes](https://www.npmjs.com/package/@tvkitchen/base-classes) package.
1. `yarn test`
- `yarn install`
Related to #5 
Relies on PR #6
=> Remove local Payload class

package.json, src/AbstractAppliance.js, src/__test__/AbstractAppliance.test.js, yarn.lock
This PR adds the IAppliance "interface" (really just a class because JavaScript).
This PR removes the newly redundant abstract method definitions from Abstractappliance.
1. `yarn test`
- `yarn install`
This resolves #5
Requires PR #7  to be merged before review should begin.
=> Use the IAppliance definition for AbstractAppliance

package.json
This PR removes package fields from the root that don't make sense any longer for a monorepo root.
1. `yarn test`
None
Resolves #20
=> Remove obsolete package fields

jest.config.json, packages/core/CHANGELOG.md, packages/core/README.md, packages/core/package.json, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, packages/core/src/__test__/classes/FullyImplementedVideoIngestionAppliance.js, packages/core/src/__test__/classes/PartiallyImplementedVideoIngestionAppliance.js, packages/core/src/__test__/classes/index.js, packages/core/src/__test__/data/getMostRecentDemuxedPacket.json, packages/core/src/__test__/data/onDemuxedPacket.json, packages/core/src/constants/events.js, packages/core/src/index.js, packages/core/src/utils/__test__/mpegts.test.js, packages/core/src/utils/mpegts.js, yarn.lock
This PR Adds a new `core` class for appliances: `AbstractIngestionAppliance`.
The AbstractIngestionAppliance converts a video stream into properly decorated Payload objects, and emits those objects in the same way any appliance would emit the Payloads it creates.
The bulk of this logic was taken directly from the old "Ingestion Engine" architecture over in the [tv-kitchen](https://github.com/tvkitchen/tv-kitchen) repository.
1. `yarn test`
This is a new feature (minor)
Related to #32
=> Add AbstractVideoIngestionAppliance

packages/file-ingestion/CHANGELOG.md, packages/file-ingestion/README.md, packages/file-ingestion/package.json, packages/file-ingestion/src/VideoFileIngestionAppliance.js, packages/file-ingestion/src/__test__/VideoFileIngestionAppliance.unit.test.js, packages/file-ingestion/src/index.js, yarn.lock
This PR adds a `video-file-ingestion` appliance, which is ported from its equivalent `FileIngestionEngine` in the tv-kitchen repository by @chriszs 
1. `yarn test`
This creates a new package.
Related to #32 
Relies on #34
=> Add Video File Ingestion Appliance

packages/video-http-ingestion/README.md, packages/video-http-ingestion/package.json, packages/video-http-ingestion/src/VideoHttpIngestionAppliance.js, packages/video-http-ingestion/src/__test__/VideoHttpIngestionEngine.unit.test.js, packages/video-http-ingestion/src/index.js, yarn.lock
This PR adds an appliance that can convert a video URL into STREAM.CONTAINER payloads.
1. `yarn test`
- `yarn install`
This is the final ingestion engine to be converted, so it resolves #32 
Relies on #36
=> Add HTTP Ingestion Appliance

packages/core/CHANGELOG.md, packages/core/src/AbstractAppliance.js, packages/core/src/AbstractVideoIngestionAppliance.js, packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/src/VideoFileIngestionAppliance.js
This PR changes the `overrideSettings` constructor parameter to `settings` in a few places.
1. `yarn test`
- This is a patch level change for all affected packages.
Resolves #39
=> Rename override settings

packages/core/CHANGELOG.md, packages/core/src/AbstractAppliance.js, packages/core/src/__test__/AbstractAppliance.test.js, packages/core/src/__test__/classes/FullyImplementedAppliance.js
Issue #41
This PR adds an `isValidPayload` method to `AbstractAppliance` which ensures that the payload is a valid type for the appliance.
It uses an assertion here (thus triggering an error) because submitting a payload of an invalid type for validation is likely a signal of a more serious problem.
1. `yarn test`
None
Resolves #41
=> Add isValidPayload to AbstractAppliance

packages/video-file-ingestion/src/VideoFileIngestionAppliance.js
This PR removes the explicit storage of `filePath` in the `VideoFileIngestionAppliance`.  That data is already stored in the `settings` instance variable.
1. `yarn test`
None
Resolves #43
=> Remove local storage of filePath

packages/ccextractor/CHANGELOG.md, packages/ccextractor/README.md, packages/ccextractor/package.json, packages/ccextractor/src/CCExtractorAppliance.js, packages/ccextractor/src/CCExtractorLine.js, packages/ccextractor/src/__test__/CCExtraactorLine.unit.test.js, packages/ccextractor/src/__test__/CCExtractorAppliance.unit.test.js, packages/ccextractor/src/index.js, packages/ccextractor/src/utils/__test__/ccextractor.unit.test.js, packages/ccextractor/src/utils/__test__/string.unit.test.js, packages/ccextractor/src/utils/ccextractor.js, packages/ccextractor/src/utils/string.js, yarn.lock
This PR adds the CCExtractorAppliance, which consumes STREAM.CONTAINER payloads and emits
TEXT.ATOM payloads.
It relies on the `CCExtractor` command line tool in order to run, and it attempts to parse the smallest possible "new" data from the CCExtractor output.
0. `yarn install`
1. `yarn test`
Without a working TV Kitchen countertop it is hard to test this appliance in full yet.
None.
Resolves #16
=> Create initial CCExtractorAppliance

packages/ccextractor/src/utils/ccextractor.js
This PR fixes the payloads that the ccextractor appliance emits, by adding the correct `TEXT.ATOM` payload type.
1. `yarn test`
None
Resolves #46
=> Add payload type to ccextractor

packages/core/src/AbstractVideoIngestionAppliance.js, packages/video-file-ingestion/package.json, packages/video-file-ingestion/src/VideoFileIngestionAppliance.js
This PR fixes the `VideoFileIngestionAppliance` by removing `start` and `stop` methods and instead relying on the `AbstractVideoIngestionAppliance` implementation (which is kind of the whole point of that class).
It also adds event emissions to the `AbstractVideoIngestionAppliance`
1. `yarn test`
- `yarn install`
Resolves #45
=> Remove start from implemented ingestion appliance

packages/core/CHANGELOG.md, packages/core/src/AbstractVideoIngestionAppliance.js
This PR fixes the ffmpeg process in AbstractVideoIngestionEngine so that the stderr buffer no longer accumulates over time.
To test this, you need a large enough video file (10 minutes of video should be enough), and to create a countertop topology that ingests that video file.  If the ingestion completes, all is well.
Resolves #53
=> Fix ffmpeg process

.eslintrc.json, packages/ccextractor/CHANGELOG.md, packages/ccextractor/src/CCExtractorAppliance.js, packages/ccextractor/src/CCExtractorLine.js, packages/ccextractor/src/__test__/CCExtraactorLine.unit.test.js, packages/ccextractor/src/__test__/CCExtractorAppliance.unit.test.js, packages/ccextractor/src/index.js, packages/ccextractor/src/utils/__test__/ccextractor.unit.test.js, packages/ccextractor/src/utils/ccextractor.js, packages/ccextractor/src/utils/string.js, packages/core/CHANGELOG.md, packages/core/src/AbstractAppliance.js, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractAppliance.test.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, packages/core/src/__test__/classes/FullyImplementedAppliance.js, packages/core/src/__test__/classes/FullyImplementedVideoIngestionAppliance.js, packages/core/src/__test__/classes/PartiallyImplementedAppliance.js, packages/core/src/__test__/classes/PartiallyImplementedVideoIngestionAppliance.js, packages/core/src/__test__/classes/index.js, packages/core/src/index.js, packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/src/VideoFileIngestionAppliance.js, packages/video-file-ingestion/src/__test__/VideoFileIngestionAppliance.unit.test.js, packages/video-file-ingestion/src/index.js, packages/video-http-ingestion/CHANGELOG.md, packages/video-http-ingestion/src/VideoHttpIngestionAppliance.js, packages/video-http-ingestion/src/__test__/VideoHttpIngestionEngine.unit.test.js, packages/video-http-ingestion/src/index.js
We never want to use default exports. There are a few reasons for this.
One is that Babel doesn't actually map them to default, which means that
require() doesn't work as expected.
The more important reason is that by using named exports we create
a consistant expectation for how to use appliances and other TVK
components, and also allow appliances to export supporting classes as
necessary.
Issue #55
This PR changes all instances of default export to use named exports.
1. `yarn test`
Resolves #55
=> Always use named exports

packages/ccextractor/CHANGELOG.md, packages/ccextractor/package.json, packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/package.json, packages/video-http-ingestion/CHANGELOG.md, packages/video-http-ingestion/package.json, yarn.lock
This PR updates the appliance-core version to `0.4.0` in order to bring the ffmpeg bug fix forward to the appliances themselves.
Related to #53
=> Update appliance core to 0.4.0

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/AbstractAppliance.js, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractAppliance.test.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, packages/core/src/__test__/classes/FullyImplementedVideoIngestionAppliance.js, packages/core/src/silentLogger.js, yarn.lock
This PR updates the appliance-core to use the Transform based IAppliance.
Appliances that extend `AbstractAppliance` will need to be updated to use the Transform API.
Related to #59
=> Update core to use Transform IAppliances

packages/ccextractor/package.json, packages/ccextractor/src/CCExtractorAppliance.js, yarn.lock
This PR updates the CCExtractorAppliance to use the latest version of `@tvkitchen/appliance-core`.  The primary change is that it now uses the node stream API.
Resolves #59
=> Update CCExtractor appliance

packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/package.json, packages/video-http-ingestion/CHANGELOG.md, packages/video-http-ingestion/package.json, yarn.lock
This PR updates the video ingestion appliances to use the latest version of appliance-core (and therefore support the node stream API)
Related to #59
=> Update video ingestion appliances

packages/ccextractor/CHANGELOG.md, packages/ccextractor/src/CCExtractorAppliance.js, packages/ccextractor/src/utils/__test__/__snapshots__/ccextractor.unit.test.js.snap, packages/ccextractor/src/utils/__test__/ccextractor.unit.test.js, packages/ccextractor/src/utils/ccextractor.js
This PR fixes a bug where the caption extraction would not emit newlines on caption line breaks.
1. `yarn test`
Resolves #66
=> Emit newline payloads

packages/core/CHANGELOG.md, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js
This PR adds support for the `timestamp` attribute for video ingestion appliances.
It also adds a new optional `origin` setting for ingestion appliances, which allows a TV Kitchen implementation to indicate what time a given video stream started (e.g. if the stream is delayed, or is pre-recorded).
Related to #76
=> Support timestamp in video ingestor appliances

packages/core/CHANGELOG.md, packages/core/src/AbstractAppliance.js, packages/core/src/__test__/AbstractAppliance.test.js
This PR fixes an issue where `invoke` could not return null without triggering an error.
Resolves #74
=> Allow null invoke returns

packages/core/CHANGELOG.md, packages/core/package.json, yarn.lock
This PR updates the version of `@tvkitchen/base-classes` to 1.4.0-alpha.2 within `appliance-core`
Resolves #81
=> Update @tvkitchen/base-classes to 1.4.0-alpha.2

package.json
This PR fixes the build script to prevent issues like #85
Specifically, running `yarn build` will wipe away the build directories before transpiling.
=> Update build logic

packages/caption-srt-generator/CHANGELOG.md, packages/caption-srt-generator/package.json, packages/ccextractor/CHANGELOG.md, packages/ccextractor/package.json, packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/package.json, packages/video-http-ingestion/CHANGELOG.md, packages/video-http-ingestion/package.json, packages/video-segment-generator/CHANGELOG.md, packages/video-segment-generator/README.md, packages/video-segment-generator/package.json
This should fix the broken build while also giving appliances access to
the latest base-class features
Issue #84
This PR updates all appliances to use the latest appliance-core version
Resolves #84
=> Update appliances to use appliance-core@0.6.1

packages/core/src/AbstractVideoIngestionAppliance.js
This PR adds flags so that ffmpeg will filter corrupt mpegts stream packets before TVK ingests the content.
The flags set are [documented here](https://ffmpeg.org/ffmpeg-codecs.html).
Resolves #94
=> Filter corrupt packets

packages/caption-srt-generator/CHANGELOG.md, packages/caption-srt-generator/src/CaptionSrtGeneratorAppliance.js, packages/core/CHANGELOG.md
This PR adds support for segments in the SRT generation.  This is needed because the actual content of the SRT payloads need to change based on segments (for instance timestamps and counters reset to zero on a new segment)
Resolves #92
=> Add segment support to the SRT Generator

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/AbstractAppliance.js, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, packages/core/src/__test__/classes/FullyImplementedAppliance.js, packages/core/src/__test__/classes/FullyImplementedVideoIngestionAppliance.js, yarn.lock
This PR removes arrow functions from core class method definitions.
It also updates the AbstractIngestionAppliance to decorate `origin` instead of `timestamp`
Resolves #100
=> Remove arrow functions from core

packages/caption-srt-generator/CHANGELOG.md, packages/caption-srt-generator/package.json, packages/core/src/AbstractAppliance.js, packages/core/src/__test__/AbstractAppliance.test.js, packages/core/src/__test__/classes/FullyImplementedAppliance.js, packages/video-caption-extractor/CHANGELOG.md, packages/video-caption-extractor/package.json, packages/video-caption-extractor/src/utils/__test__/__snapshots__/ccextractor.unit.test.js.snap, packages/video-segment-generator/CHANGELOG.md, packages/video-segment-generator/package.json, packages/video-segment-generator/src/utils/__test__/__snapshots__/segment.test.js.snap, yarn.lock
This PR updates appliances so that they all use the new `origin` Payloads (as opposed to `timestamp` Payloads).
This PR also updates the appliance core classes so that appliances will now all generate payloads with populated `origin` values.
Resolves #103
=> Support `origin` Payloads

packages/core/CHANGELOG.md, packages/core/src/AbstractAppliance.js, packages/core/src/AbstractVideoIngestionAppliance.js
This PR fixes an issue where origin was not being properly looked up and applied to outbound payloads.
It also fixes an issue with the `AbstractVideoIngestionAppliance` where it event handlers were not being properly bound to `this`.
Related to #103
=> Some origin fixes

packages/video-segment-generator/CHANGELOG.md, packages/video-segment-generator/README.md, packages/video-segment-generator/src/VideoSegmentGeneratorAppliance.js, packages/video-segment-generator/src/utils/__test__/__snapshots__/segment.test.js.snap, packages/video-segment-generator/src/utils/__test__/segment.test.js, packages/video-segment-generator/src/utils/segment.js
The VideoSegmentGenerator appliance was using the old `timestamp` field
and needed to be updated to use `origin`.  This also helped highlight
some of the difficult-to-parse variable and method names.
Instead of using `origin` in the segment appliance, it is `startingAt`
which has more intuitive meaning.  Some of the internal methods have
been reworded as well with the goal of legibility.
Issue #103
This PR updates the `VideoSegmentGeneratorAppliance` to use the new `origin` Payload.
This also involved renaming some internal variables and methods so the term `origin` wouldn't be overloaded.
Note that it's hard to name variables that exist to resolve two separate time frames that are moving forward in parallel... but I do think these names are an improvement.
Related to #103
=> Refactor segment generator

packages/video-caption-extractor/src/VideoCaptionExtractorAppliance.js
This PR fixes an issue where the `VideoCaptionExtractorAppliance` would stop emitting captions due to the process stdio getting backed up.
Resolves #112 
Related to #53
=> Ignore stderr in CCExtractor process

packages/caption-srt-generator/README.md, packages/video-caption-extractor/README.md, packages/video-file-ingestion/README.md, packages/video-http-ingestion/README.md, packages/video-segment-generator/README.md
Input and output table formatting in README.md files of each appliance
misrender in Github-flavored MD. This commit fixes that issue.
Issue #102
1. `yarn test`
N/A
Resolves #102
=> Fix appliance documentation formatting (Issue #102)

packages/core/package.json, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, yarn.lock
This PR changes our MPEG-TS demuxing script from `ts-demuxer` to our newly released `mpegts-demuxer`.
The forked version of the library changes the API to support NodeJS Streams, and also fixes a few of the bugs that we've recently uncovered related to timestamp extraction.
Resolves #117 
Resolves #97 
Resolves #111
=> Use mpegts-demuxer

packages/video-caption-extractor/CHANGELOG.md, packages/video-caption-extractor/src/utils/__test__/ccextractor.unit.test.js, packages/video-caption-extractor/src/utils/ccextractor.js
This PR fixes an issue where CCExtractor's occasional `00:00:00` timestamps for caption strings would create payloads with wild and crazy duration / position values.
Resolves #109 
Resolves #107
=> Handle zero values in CCExtractorLines

package.json, yarn.lock
This PR repalces `rm -fr` with `rimraf` when building / running `yarn clean`
Resolves #119
=> Use rimraf for cleaning

package.json
This PR removes some yarn hooks that were just creating a bunch of noise on `test` and `lint`.
Resolves #122
=> Remove hooks from base package

packages/caption-srt-generator/CHANGELOG.md, packages/caption-srt-generator/package.json, packages/video-caption-extractor/CHANGELOG.md, packages/video-caption-extractor/package.json, packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/package.json, packages/video-http-ingestion/CHANGELOG.md, packages/video-http-ingestion/package.json, packages/video-segment-generator/CHANGELOG.md, packages/video-segment-generator/package.json
This PR updates `@tvkitchen/appliance-core` to `0.7.0` for all appliances.
I'm trying a thing where I don't make an issue for this kind of bulk version update, but that's probably not a good plan.
=> Update core to 0.7.0

packages/core/CHANGELOG.md, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, packages/core/src/utils/__test__/mpegts.test.js, packages/core/src/utils/mpegts.js
This PR adds support for PTS rollovers, which occur around every 26.5 hours (every `2^33 / 90` seconds).
Ingestion appliances that extend the `AbstractVideoIngestionAppliance` should see this support without any needed changes.
Resolves #130
=> Handle PTS rollovers

packages/core/CHANGELOG.md, packages/core/src/AbstractVideoIngestionAppliance.js, packages/core/src/__test__/AbstractVideoIngestionAppliance.test.js, packages/core/src/__test__/data/getMostRecentDemuxedPacket.json, packages/core/src/__test__/data/onDemuxedPacket.json, packages/core/src/__test__/data/processMpegtsStreamData.json
This PR fixes an issue where both video and audio stream positions were tracked, resulting in false rollovers.
Resolves #132
=> Only track video streams

packages/video-file-ingestion/CHANGELOG.md, packages/video-file-ingestion/package.json, packages/video-http-ingestion/CHANGELOG.md, packages/video-http-ingestion/package.json, yarn.lock
This PR updates the appliance core to `v0.7.1` for ingestion appliances in order to benefit from the PTS rollover logic.
Related to #130
=> Update appliance-core for ingestion appliances

packages/video-caption-extractor/src/VideoCaptionExtractorAppliance.js, packages/video-caption-extractor/src/utils/__test__/__snapshots__/ccextractor.unit.test.js.snap, packages/video-caption-extractor/src/utils/__test__/ccextractor.unit.test.js, packages/video-caption-extractor/src/utils/ccextractor.js, packages/video-caption-extractor/src/utils/payload.js
This PR changes the way captions are loaded from CCExtractor so that entire (finalized) lines are loaded at once, rather than trying to extract characters as they are parsed.
Resolves #133
=> Load CCExtractor lines all at once

packages/core/CHANGELOG.md, packages/core/src/AbstractAppliance.js, packages/core/src/__test__/AbstractAppliance.test.js, packages/core/src/__test__/classes/DynamicTypeAppliance.js, packages/core/src/__test__/classes/index.js
This PR updates the AbstractAppliance's implementation of `isValidPayload` to pass the current instance's settings to the `getInputTypes` method.  The settings might be ignored, but by passing them it becomes possible for an appliance author to accept different payload types depending on the appliance's settings.
(This change will also need to be made in the countertop)
Related to #151
=> Support dynamic input / output types

packages/core/CHANGELOG.md, packages/core/package.json, yarn.lock
This PR updates the version of the @tvkitchen/base-interfaces to latest.
=> Update base-interfaces to v4.0.0-alpha.5
